// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportResults(arg1) {
  return window['go']['main']['App']['ExportResults'](arg1);
}

export function GetLocalIPRange() {
  return window['go']['main']['App']['GetLocalIPRange']();
}

export function ParseRange(arg1) {
  return window['go']['main']['App']['ParseRange'](arg1);
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
