// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {diff} from '../models';
import {results} from '../models';
import {store} from '../models';
import {profile} from '../models';

export function CompareScans(arg1:number,arg2:number):Promise<Array<diff.HostDiff>>;

export function DeleteScan(arg1:number):Promise<void>;

export function ExportResults(arg1:Array<results.HostResult>):Promise<string>;

export function GetLocalIPRange():Promise<string>;

export function GetMAC(arg1:string):Promise<string>;

export function GetScanReport(arg1:number):Promise<results.ScanReport>;

export function GetScans():Promise<Array<store.ScanSummary>>;

export function ParseRange(arg1:string):Promise<Array<string>>;

export function Ping(arg1:string):Promise<boolean>;

export function ReverseDNS(arg1:string):Promise<string>;

export function ScanPorts(arg1:string,arg2:Array<number>):Promise<Array<number>>;

export function StartScan(arg1:Array<string>,arg2:profile.ScanProfile):Promise<void>;

export function StopScan():Promise<void>;
