// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {results} from '../models';
import {engine} from '../models';

export function ExportResults(arg1:Array<results.DeviceInfo>):Promise<string>;

export function GetLocalIPRange():Promise<string>;

export function ParseRange(arg1:string):Promise<Array<string>>;

export function StartScan(arg1:Array<string>,arg2:engine.ScanConfig):Promise<void>;

export function StopScan():Promise<void>;
