// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CompareScans(arg1, arg2) {
  return window['go']['main']['App']['CompareScans'](arg1, arg2);
}

export function DeleteScan(arg1) {
  return window['go']['main']['App']['DeleteScan'](arg1);
}

export function ExportResults(arg1) {
  return window['go']['main']['App']['ExportResults'](arg1);
}

export function GetLocalIPRange() {
  return window['go']['main']['App']['GetLocalIPRange']();
}

export function GetMAC(arg1) {
  return window['go']['main']['App']['GetMAC'](arg1);
}

export function GetScanReport(arg1) {
  return window['go']['main']['App']['GetScanReport'](arg1);
}

export function GetScans() {
  return window['go']['main']['App']['GetScans']();
}

export function ParseRange(arg1) {
  return window['go']['main']['App']['ParseRange'](arg1);
}

export function Ping(arg1) {
  return window['go']['main']['App']['Ping'](arg1);
}

export function ReverseDNS(arg1) {
  return window['go']['main']['App']['ReverseDNS'](arg1);
}

export function ScanPorts(arg1, arg2) {
  return window['go']['main']['App']['ScanPorts'](arg1, arg2);
}

export function StartScan(arg1, arg2) {
  return window['go']['main']['App']['StartScan'](arg1, arg2);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
