// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {scanner} from '../models';

export function ExportResults(arg1:Array<scanner.DeviceInfo>):Promise<string>;

export function GetLocalIPRange():Promise<string>;

export function GetMAC(arg1:string):Promise<string>;

export function ParseRange(arg1:string):Promise<Array<string>>;

export function Ping(arg1:string):Promise<boolean>;

export function ReverseDNS(arg1:string):Promise<string>;

export function ScanPorts(arg1:string,arg2:Array<number>):Promise<Array<number>>;

export function StartScan(arg1:Array<string>,arg2:scanner.ScanConfig):Promise<void>;

export function StopScan():Promise<void>;
