name: Auto Merge PR

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"