name: CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout catnet-scanner
        uses: actions/checkout@v4.2.2
        with:
          path: catnet-scanner

      - name: Checkout catnet-core
        uses: actions/checkout@v4.2.2
        with:
          repository: mendsec/catnet-core
          ref: fix/add-compat-packages-for-catnet-scanner
          path: catnet-core

      - name: Setup Go
        uses: actions/setup-go@v5.1.0
        with:
          go-version: '1.26.x'
          
      - name: Install Linux Dependencies
        run: sudo apt-get update && sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.1-dev

      - name: Mock frontend dist
        working-directory: catnet-scanner
        run: mkdir -p frontend/dist; echo "mock" > frontend/dist/index.html

      - name: Backend test
        working-directory: catnet-scanner
        env:
          CGO_ENABLED: 1
        run: go test -race -v ./...

  frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout catnet-scanner
        uses: actions/checkout@v4.2.2
        with:
          path: catnet-scanner

      - name: Checkout catnet-core
        uses: actions/checkout@v4.2.2
        with:
          repository: mendsec/catnet-core
          ref: fix/add-compat-packages-for-catnet-scanner
          path: catnet-core

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        working-directory: catnet-scanner/frontend
        run: bun install

      - name: Build frontend
        working-directory: catnet-scanner/frontend
        run: bun run build
