name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.23' # Use a version that supports wails requirements

    - name: Verify dependencies
      run: go mod verify

    - name: Set up Bun
      uses: oven-sh/setup-bun@v2

    - name: Build Frontend
      run: |
        cd frontend
        bun install
        bun run build

    - name: Vet
      run: go vet ./...

    - name: Test
      env:
        CGO_ENABLED: 1
      run: go test -race -v ./...
